ALTER TABLE accounts
  DROP COLUMN type,
  DROP COLUMN currency,
  DROP COLUMN balance,
  ADD COLUMN IF NOT EXISTS balance NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK (balance >= 0),
  ADD COLUMN account_number VARCHAR(10) NOT NULL UNIQUE,
  ADD COLUMN bank_code VARCHAR(3) NOT NULL,
  ADD COLUMN bank_name VARCHAR(100) NOT NULL;